# London Bike Sharing

In [82]:
# Importing libraries
import pandas as pd
import zipfile
import kaggle

from kaggle.api.kaggle_api_extended import KaggleApi

In [83]:
# API for kaggle datasets
api = KaggleApi()
api.authenticate()

In [84]:
# Downloading data
!kaggle datasets download -d hmavrodiev/london-bike-sharing-dataset

london-bike-sharing-dataset.zip: Skipping, found more recently modified local copy (use --force to force download)

In [85]:
# Extracting data
zipfile_name = 'london-bike-sharing-dataset.zip'
with zipfile.ZipFile(zipfile_name, 'r') as file:
    file.extractall()

In [86]:
# Reading in the csv file created
bikes = pd.read_csv("london_merged.csv")

In [87]:
# Exploring the dataset
bikes.info()
bikes.shape

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17414 entries, 0 to 17413
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   timestamp     17414 non-null  object
 1   cnt           17414 non-null  int64
 2   t1            17414 non-null  float64
 3   t2            17414 non-null  float64
 4   hum           17414 non-null  float64
 5   wind_speed    17414 non-null  float64
 6   weather_code  17414 non-null  float64
 7   is_holiday    17414 non-null  float64
 8   is_weekend    17414 non-null  float64
 9   season        17414 non-null  float64
dtypes: float64(8), int64(1), object(1)
memory usage: 1.3+ MB

(17414, 10)

In [88]:
bikes

,timestamp,cnt,t1,t2,hum,wind_speed,weather_code,is_holiday,is_weekend,season
0,2015-01-04 00:00:00,182,3.0,2.0,93.0,6.0,3.0,0.0,1.0,3.0
1,2015-01-04 01:00:00,138,3.0,2.5,93.0,5.0,1.0,0.0,1.0,3.0
2,2015-01-04 02:00:00,134,2.5,2.5,96.5,0.0,1.0,0.0,1.0,3.0
3,2015-01-04 03:00:00,72,2.0,2.0,100.0,0.0,1.0,0.0,1.0,3.0
4,2015-01-04 04:00:00,47,2.0,0.0,93.0,6.5,1.0,0.0,1.0,3.0
...,...,...,...,...,...,...,...,...,...,...
17409,2017-01-03 19:00:00,1042,5.0,1.0,81.0,19.0,3.0,0.0,0.0,3.0
17410,2017-01-03 20:00:00,541,5.0,1.0,81.0,21.0,4.0,0.0,0.0,3.0
17411,2017-01-03 21:00:00,337,5.5,1.5,78.5,24.0,4.0,0.0,0.0,3.0
17412,2017-01-03 22:00:00,224,5.5,1.5,76.0,23.0,4.0,0.0,0.0,3.0
17413,2017-01-03 23:00:00,139,5.0,1.0,76.0,22.0,2.0,0.0,0.0,3.0

In [89]:
# Couinting the unique weather code 
bikes.weather_code.value_counts()

1.0     6150
2.0     4034
3.0     3551
7.0     2141
4.0     1464
26.0      60
10.0      14
Name: weather_code, dtype: int64

In [90]:
# Count the unique vbalues in the season column
bikes.season.value_counts()

0.0    4394
1.0    4387
3.0    4330
2.0    4303
Name: season, dtype: int64

In [91]:
# Defining a dictionary (for easy namimg)
new_cols_dict = {
'timestamp':'time',
'cnt':'count',
't1':'temp_real_C',
't2':'temp_feels_like_C',
'hum':'humidity_percent',
'wind_speed':'wind_speed_kph',
'weather_code': 'weather',
'is_holiday':'is_holiday',
'is_weekend':'is_weekend',
'season':'season'
}

# Renaming columns
bikes.rename(new_cols_dict, axis = 1, inplace = True)

In [92]:
# Changing the humidity values to a value from 100%
bikes.humidity_percent = bikes.humidity_percent/100

In [93]:
# Checking values to see if the data is correct
bikes.humidity_percent[1:10,]

1    0.930
2    0.965
3    1.000
4    0.930
5    0.930
6    1.000
7    1.000
8    0.965
9    1.000
Name: humidity_percent, dtype: float64

In [94]:
# Making a seasons and weather dictionary
seasons_dict = {
'0.0': 'spring',
'1.0': 'summer',
'2.0': 'autumn',
'3.0': 'winter'
}

weather_dict = {
'1.0':'Clear',
'2.0': 'Scattered Clouds',
'3.0': 'Broken clouds',
'4.0': 'Cloudy',
'7.0': 'Rain',
'10.0': 'Rain with thunderstorm',
'26.0': 'Snowfall'
}

In [95]:
# Manipulating vlaues of the column(s)
bikes.season = bikes.season.astype('str')

# Using map function
bikes.season = bikes.season.map(seasons_dict)

# Weather
bikes.weather = bikes.weather.astype('str')

# Mapping function to replace
bikes.weather = bikes.weather.map(weather_dict)

In [96]:
# Checking to see if data has been changed successfully
bikes.head()

,time,count,temp_real_C,temp_feels_like_C,humidity_percent,wind_speed_kph,weather,is_holiday,is_weekend,season
0,2015-01-04 00:00:00,182,3.0,2.0,0.930,6.0,Broken clouds,0.0,1.0,winter
1,2015-01-04 01:00:00,138,3.0,2.5,0.930,5.0,Clear,0.0,1.0,winter
2,2015-01-04 02:00:00,134,2.5,2.5,0.965,0.0,Clear,0.0,1.0,winter
3,2015-01-04 03:00:00,72,2.0,2.0,1.000,0.0,Clear,0.0,1.0,winter
4,2015-01-04 04:00:00,47,2.0,0.0,0.930,6.5,Clear,0.0,1.0,winter

In [97]:
# Mapping the is_holiday and _is.weekend fields
holiday_dict = {
'0.0':'No',
'1.0':'Yes'
}

weekend_dict = {
'0.0':'No',
'1.0':'Yes'
}


# Revising the data attributes for mapping
bikes.is_holiday = bikes.is_holiday.astype('str')
bikes.is_weekend = bikes.is_weekend.astype('str')

# Mapping
bikes.is_holiday = bikes.is_holiday.map(holiday_dict)
bikes.is_weekend = bikes.is_weekend.map(weekend_dict)

In [98]:
# Checking the results
bikes.head(10)

,time,count,temp_real_C,temp_feels_like_C,humidity_percent,wind_speed_kph,weather,is_holiday,is_weekend,season
0,2015-01-04 00:00:00,182,3.0,2.0,0.930,6.0,Broken clouds,No,Yes,winter
1,2015-01-04 01:00:00,138,3.0,2.5,0.930,5.0,Clear,No,Yes,winter
2,2015-01-04 02:00:00,134,2.5,2.5,0.965,0.0,Clear,No,Yes,winter
3,2015-01-04 03:00:00,72,2.0,2.0,1.000,0.0,Clear,No,Yes,winter
4,2015-01-04 04:00:00,47,2.0,0.0,0.930,6.5,Clear,No,Yes,winter
5,2015-01-04 05:00:00,46,2.0,2.0,0.930,4.0,Clear,No,Yes,winter
6,2015-01-04 06:00:00,51,1.0,-1.0,1.000,7.0,Cloudy,No,Yes,winter
7,2015-01-04 07:00:00,75,1.0,-1.0,1.000,7.0,Cloudy,No,Yes,winter
8,2015-01-04 08:00:00,131,1.5,-1.0,0.965,8.0,Cloudy,No,Yes,winter
9,2015-01-04 09:00:00,301,2.0,-0.5,1.000,9.0,Broken clouds,No,Yes,winter

In [99]:
# Finalising data manipulation and creating excel sheet for Tableau visualisation

try:
    bikes.to_excel('london_bikes_final.xlsx', sheet_name='Data')
    print("File written successfully.")
except FileExistsError:
    # Handle the case where the file already exists
    print("File already exists. It will be replaced.")

File written successfully.